### ISSUE TITLE
Add editor checklist

### ISSUE THREAD

**Issue by ligi** [efdevcon/DIPs#22]
we have a checklist in notion - but it would be good to have it here to be more transparent about the process, maybe have less iterations (as contributors know what will be checked) and being able to accept improvements to the list.

 * [ ] Correct markdown (e.g. headers with ##, header surrounded by ---)
 * [ ] syntax check
 * [ ] filename is DIP-X.md (with X being the correct DIP number)
 * [ ] header contains (in this order)
   * [ ] DIP
   * [ ] Title
   * [ ] Theme
   * [ ] Tags
   * [ ] Author
   * [ ] Resources Required
   * [ ] Discussion-to (with link to devcon forum)
   * [ ] Created
 * [ ] contains these sections:
   * [ ] Abtract
   * [ ] Rationale
   * [ ] Implementation
   * [ ] Operational Reuirements & Ownership
 * [ ] PR title prefixed with DIP-X:

**Comment by skylarweaver** [comment]
I agree, let's do this!
